version: 2
registries:
  fortawesome:
    type: "npm-registry"
    url: "https://npm.fontawesome.com/"
    token: ${{secrets.FONT_AWESOME_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
  - package-ecosystem: "npm"
    registries:
      - fortawesome
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
