name: 🤖 Dependabot auto-merge

on: [pull_request]

permissions:
  contents: write
  pull-requests: write

jobs:
  call-auto-merge-workflow:
    if: ${{ github.actor == 'dependabot[bot]' }}
    uses: mikesprague/reusable-workflows/.github/workflows/dependabot-auto-merge.yml@main
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
